from py2neo import Graph,Node,Relationship

graph = Graph(password="12345678")

node1 = Node("Person", name ="Hamza")
graph.create(node1)
node2 = Node("Object" ,name = "Waggoner")
graph.create(node2)
relationship1 = Relationship(node1,"has",node2)
graph.create(relationship1)
node3 = Node("Color" , name = "White")
graph.create(node3)
relationship2 = Relationship(node2,"color_is",node3)
graph.create(relationship2)
node4 = Node("Person", name = "Ali")
graph.create(node4)
relationship3= Relationship(node4,"friend_of",node1)
graph.create(relationship3)
node5 = Node("Object" , name = "Car")
graph.create(node5)
relationship4= Relationship(node4,"loves_to_Drive",node5)
graph.create(relationship4)
relationship5= Relationship(node1,"gave",node2)
graph.create(relationship5)
relationship6= Relationship(node2,"to",node4)
graph.create(relationship6)
node6 = Node("Animal", name = "pet")
graph.create(node6)
relationship7= Relationship(node1,"has a",node6)
graph.create(relationship7)
node7 = Node("pet", name = "monkey")
graph.create(node7)
relationship8= Relationship(node6,"is a",node7)
graph.create(relationship8)
node8 = Node("name", name = "Tony")
graph.create(node8)
relationship9= Relationship(node6,"name",node8)
graph.create(relationship9)
relationship10= Relationship(node7,"sits",node2)
graph.create(relationship10)
node9 = Node("Place", name = "University")
graph.create(node9)
relationship11= Relationship(node1,"goes to",node9)
graph.create(relationship11)
relationship12= Relationship(node4,"goes to",node9)
graph.create(relationship12)


