from py2neo import Graph, Node, Relationship
graph = Graph(password="12345678")
# graph.run("CREATE(n:Person{name:'Ariba'})")
node1 = Node("Animal", name="Cat")
graph.create(node1)
node2 = Node("Object", name="Fur")
graph.create(node2)
relationship = Relationship(node1,"has",node2)
graph.create(relationship)
node3 = Node("Animal", name="Fish")
graph.create(node3)
relationship2 = Relationship(node1,"eats",node3)
graph.create(relationship2)
node4 = Node("Object", name="Water")
graph.create(node4)
relationship3 = Relationship(node3, "lives", node4)
graph.create(relationship3)